name: Staging Migrations

on:
  push:
    branches: [ staging ]

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Supabase CLI
        run: brew install supabase/tap/supabase
      - name: Set Remote DB
        shell: bash
        env:
          SUPABASE_PASSWORD: ${{ secrets.STAGING_SUPABASE_PASSWORD }}
          SUPABASE_PROJECT_REF: ${{ secrets.STAGING_SUPABASE_PROJECT_REF }}
        run: |
          supabase db remote set 'postgresql://supabase_admin:"$SUPABASE_PASSWORD"@db."$SUPABASE_PROJECT_REF".supabase.co:5432/postgres'
      - name: Push Migrations
        run: supabase db push
